language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: asampaio  
